name: explainIssue
on:
  issues:
    types: opened

jobs:
  explainDetails:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: explain issue details
        run: echo "This issue was opened. Title -> ${{ toJSON(github.event.issue.title)}} Description -> ${{ github.event.issue.body }}"
      